import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import Header from "@/components/layout/Header";
import "./globals.css";
import { MainNavigation } from "@/components/layout/MainNavigation";

const RobotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const RobotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${RobotoSans.variable} ${RobotoMono.variable} antialiased`}
      >
        <div className="mx-auto grid min-h-screen max-w-[1920px] grid-rows-[min-content_1fr_min-content]">
          <Header className="bg-brand-body mx-auto w-full text-white" />
          <main className="relative">
            <MainNavigation className="absolute z-10 w-full" />

            {children}
          </main>
          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
