export { Car } from "./icon/Car";
export { CarRepair } from "./icon/CarRepair";
export { CarSecurity } from "./icon/CarSecurity";
export { Geo } from "./icon/Geo";
export { Cloak } from "./icon/Cloak";
export { Tel } from "./icon/Tel";
export { List } from "./icon/List";
export { Quality } from "./icon/Quality";
export { IconInstagram } from "./icon/IconInstagram";
export { Logo } from "./icon/Logo";
export { Worker } from "./icon/glassReplacement/Worker";
export { Consultation } from "./icon/glassReplacement/Consultation";
export { EEClogo } from "./icon/glassReplacement/EEClogo";
export { QualityMedal } from "./icon/glassReplacement/QualityMedal";
export { Car2 } from "./icon/glassReplacement/Car2";
export { Bus } from "./icon/glassReplacement/Bus";
export { Tractor } from "./icon/glassReplacement/Tractor";
export { Truck } from "./icon/glassReplacement/Truck";
export { default as servicesImage1 } from "./img/services/1.webp";
export { default as servicesImage2 } from "./img/services/2.webp";
export { default as servicesImage3 } from "./img/services/3.webp";
export { default as servicesImage4 } from "./img/services/4.webp";
export { default as carouselImage1 } from "./img/carousel/carouselImage1.webp";
export { default as carouselImage2 } from "./img/carousel/carouselImage2.webp";
export { default as carouselImage3 } from "./img/carousel/carouselImage3.webp";
export { default as imgForm } from "./img/imageForm.webp";
export { default as replacement1 } from "./img/glass-replacement/sectionMain.webp";
export { default as replacement2 } from "./img/glass-replacement/image1.webp";
export { default as replacement3 } from "./img/glass-replacement/image2.webp";
export { default as replacement4 } from "./img/glass-replacement/image3.webp";
export { default as replacement5 } from "./img/glass-replacement/image4.webp";
export { default as serviceCar } from "./img/glass-replacement/serviceCar.webp";
export { default as repair1 } from "./img/chipRepair/repair1.webp";
export { default as repair2 } from "./img/chipRepair/repair2.webp";
export { default as repair3 } from "./img/chipRepair/repair3.webp";
export { default as repair4 } from "./img/chipRepair/repair4.webp";
export { default as repair5 } from "./img/chipRepair/repair5.webp";
export { default as polishing1 } from "./img/headlightPolishing/polishing1.webp";
