export { Car } from "./icon/Car";
export { CarRepair } from "./icon/CarRepair";
export { CarSecurity } from "./icon/CarSecurity";
export { Geo } from "./icon/Geo";
export { Cloak } from "./icon/Cloak";
export { Tel } from "./icon/Tel";
export { List } from "./icon/List";
export { Quality } from "./icon/Quality";
export { IconInstagram } from "./icon/IconInstagram";
export { Logo } from "./icon/Logo";
export { default as servicesImage1 } from "./img/services/1.webp";
export { default as servicesImage2 } from "./img/services/2.webp";
export { default as servicesImage3 } from "./img/services/3.webp";
export { default as servicesImage4 } from "./img/services/4.webp";
export { default as carouselImage1 } from "./img/carousel/carouselImage1.webp";
export { default as carouselImage2 } from "./img/carousel/carouselImage2.webp";
export { default as carouselImage3 } from "./img/carousel/carouselImage3.webp";
export { default as imgForm } from "./img/imageForm.webp";
